from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from pydantic import BaseModel, Field
from app.core.config import settings
from typing import Literal

class NegotiationResult(BaseModel):
    intent: Literal["promise_to_pay", "request_split", "general_query", "unknown"] = Field(description="The customer's intent")
    reply_message: str = Field(description="The response message generated by the agent")
    action_taken: str = Field(description="Internal description of what the agent did (e.g. 'Created split payment link', 'Logged promise')")

class NegotiationAgent:
    def __init__(self):
        self.llm = ChatGroq(
            model=settings.llm_model,
            temperature=0.2,
            api_key=settings.groq_api_key,
        )
        self.structured_llm = self.llm.with_structured_output(NegotiationResult)

        self.prompt = ChatPromptTemplate.from_messages([
            ("system", """
You are a smart AI Negotiation Agent for RecoverAI.
A customer has replied to an automated payment reminder.
Analyze their reply and decide how to respond to maximize revenue recovery.

Intent Classification:
- 'promise_to_pay': Customer says they will pay later or tomorrow.
- 'request_split': Customer mentions they don't have the full amount or asks to pay partially/in installments.
- 'general_query': Customer asks why the payment failed or a general question.
- 'unknown': Any other reply.

Response Rules:
1. Always reply in the same language the customer used.
2. Be empathetic and professional.
3. If 'promise_to_pay', thank them and confirm the date.
4. If 'request_split', offer to split the bill into 2 equal parts and provide [SPLIT_LINK_1].
5. Keep it concise (1-2 sentences).
"""),
            ("human", """
Transaction ID: {transaction_id}
Original Amount: ₹{amount}
Customer Reply: "{customer_message}"
""")
        ])

    def negotiate(self, transaction_id: str, amount: float, customer_message: str) -> NegotiationResult:
        chain = self.prompt | self.structured_llm
        result = chain.invoke({
            "transaction_id": transaction_id,
            "amount": amount,
            "customer_message": customer_message,
        })
        return result
